### PR TITLE
Add github workflow

### PR DESCRIPTION
**Pull request by powli**
Add jobs for phpunit, ecs and psalm

### CODE REVIEW

**Comment by SebastianFranze** [comment]
Hey there and sorry for the late answer. Thank you for the contribution

LGTM, but is it possible to use our make commands instead? Should we better move them to composer scripts to not leave the PHP stack?

**Comment by powli** [comment]
I personally would prefer to move them to composer scripts because you are able to pass extra options to the script with e.g. `composer run ecs-dry -- --ansi`. This enables the scripts to be aimed at a dev environment and the CI to add additional arguments for its need.

**Comment by SebastianFranze** [comment]
Yes, I think creating composer commands would be more efficient.

I don't know if there is a way to pass command-line arguments to make, either. I only know that you can only pass environment variables to scripts or you have to build a very complex target to read variables. Additionally, Ubuntu does not ship with make installed. So we'd have to install it on the GitHub flow. The only benefit of make is that you can have dependencies that are run if a folder does not exist.

Looks pretty good with the composer commands :smiley:

**Comment by powli** [comment]
I ported the scripts to composer scripts and made the bin-plugin to always install it's dependencies now. Pipeline is succeeding again too.

**Review by SebastianFranze — APPROVED** [review]

**Review by Christian-Rades — APPROVED** [review]

**Pull request merged**
